language: python
python:
    - "2.7"
    - "3.6"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends ruby-sass
install:
    - pip install nose
    - pip install -e git://github.com/getpelican/pelican.git#egg=pelican
    - pip install beautifulsoup4 cssutils disqus-python gensim gitpython google-api-python-client google_compute_engine
    - pip install html5lib icalendar ipython lxml Markdown Pillow praw pysvg python-hglib requests rst2pdf xhtml2pdf unity
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install webassets cssmin; fi
script: nosetests
